@startuml diagrama-contexto-administrador

left to right direction
skinparam linetype polyline

state "NO_AUTENTICADO" as NoAuth
state "AUTENTICANDO" as PreMenu
state "MENU_PRINCIPAL" as Menu

state "PROGRAMAS_ABIERTO" as ListProgramas
state "PROGRAMA_ABIERTO" as EditPrograma
state "CURSOS_ABIERTO" as ListCursos
state "CURSO_ABIERTO" as EditCurso
state "PROFESORES_ABIERTO" as ListProfesores
state "PROFESOR_ABIERTO" as EditProfesor
state "PROFESOR_PREFERENCIAS_ABIERTO" as EditProfesorPreferencias
state "EDIFICIOS_ABIERTO" as ListEdificios
state "EDIFICIO_ABIERTO" as EditEdificio
state "AULAS_ABIERTO" as ListAulas
state "AULA_ABIERTA" as EditAula
state "RECURSOS_ABIERTO" as ListRecursos
state "RECURSO_ABIERTO" as EditRecurso

state "CONFIGURANDO_ASIGNACIONES" as Asignaciones
state "GENERANDO_HORARIO" as Generacion
state "CONSULTANDO_HORARIOS" as Consulta

[*] --> NoAuth

PreMenu --> NoAuth
    note on link
        iniciarSesion(error)
    end note

NoAuth --> PreMenu
    note on link
        iniciarSesion()
    end note

PreMenu --> Menu
    note on link
        mostrarMenu()
    end note

Menu --> NoAuth
    note on link
        cerrarSesion()
    end note

Menu --> ListProgramas
    note on link
        abrirProgramas()
    end note

Menu --> ListCursos
    note on link
        abrirCursos()
    end note

Menu --> ListProfesores
    note on link
        abrirProfesores()
    end note

Menu --> ListEdificios
    note on link
        abrirEdificios()
    end note

Menu --> ListAulas
    note on link
        abrirAulas()
    end note

Menu --> ListRecursos
    note on link
        abrirRecursos()
    end note

Menu --> Asignaciones
    note on link
        asignarProfesorACurso()
    end note

Menu --> Generacion
    note on link
        generarHorario()
    end note

Menu --> Consulta
    note on link
        consultarHorario()
    end note

ListProgramas --> EditPrograma
    note on link
        crearPrograma()
    end note

ListProgramas --> EditPrograma
    note on link
        editarPrograma()
    end note

ListProgramas --> ListProgramas
    note on link
        eliminarPrograma()
    end note

EditPrograma --> EditPrograma
    note on link
        editarPrograma()
    end note

EditPrograma --> ListProgramas
    note on link
        abrirProgramas()
    end note

ListCursos --> EditCurso
    note on link
        crearCurso()
    end note

ListCursos --> EditCurso
    note on link
        editarCurso()
    end note

ListCursos --> ListCursos
    note on link
        eliminarCurso()
    end note

EditCurso --> EditCurso
    note on link
        editarCurso()
    end note

EditCurso --> ListCursos
    note on link
        abrirCursos()
    end note

ListProfesores --> EditProfesor
    note on link
        crearProfesor()
    end note

ListProfesores --> EditProfesor
    note on link
        editarProfesor()
    end note

ListProfesores --> ListProfesores
    note on link
        eliminarProfesor()
    end note

EditProfesor --> EditProfesor
    note on link
        editarProfesor()
    end note

EditProfesor --> EditProfesorPreferencias
    note on link
        configurarPreferenciasProfesor()
    end note

EditProfesorPreferencias --> EditProfesor
    note on link
        abrirEdicionProfesor()
    end note
    
EditProfesor --> ListProfesores
    note on link
        abrirProfesores()
    end note

ListEdificios --> EditEdificio
    note on link
        crearEdificio()
    end note

ListEdificios --> EditEdificio
    note on link
        editarEdificio()
    end note

ListEdificios --> ListEdificios
    note on link
        eliminarEdificio()
    end note

EditEdificio --> EditEdificio
    note on link
        editarEdificio()
    end note

EditEdificio --> ListEdificios
    note on link
        abrirEdificios()
    end note

ListAulas --> EditAula
    note on link
        crearAula()
    end note

ListAulas --> EditAula
    note on link
        editarAula()
    end note

ListAulas --> ListAulas
    note on link
        eliminarAula()
    end note

EditAula --> EditAula
    note on link
        editarAula()
    end note

EditAula --> ListAulas
    note on link
        abrirAulas()
    end note

ListRecursos --> EditRecurso
    note on link
        crearRecurso()
    end note

ListRecursos --> EditRecurso
    note on link
        editarRecurso()
    end note

ListRecursos --> ListRecursos
    note on link
        eliminarRecurso()
    end note

EditRecurso --> EditRecurso
    note on link
        editarRecurso()
    end note

EditRecurso --> ListRecursos
    note on link
        abrirRecursos()
    end note

ListProgramas --> Menu
    note on link
        mostrarMenu()
    end note

ListCursos --> Menu
    note on link
        mostrarMenu()
    end note

ListProfesores --> Menu
    note on link
        mostrarMenu()
    end note

ListEdificios --> Menu
    note on link
        mostrarMenu()
    end note

ListAulas --> Menu
    note on link
        mostrarMenu()
    end note

ListRecursos --> Menu
    note on link
        mostrarMenu()
    end note

Asignaciones --> Menu
    note on link
        mostrarMenu()
    end note

Generacion --> Menu
    note on link
        mostrarMenu()
    end note

Consulta --> Menu
    note on link
        mostrarMenu()
    end note

@enduml