@startuml mostrarMenu-analisis
skinparam linetype polyline

actor Administrador
package mostrarMenu as "mostrarMenu()" {
    rectangle #629EF9 MenuView
    rectangle #b5bd68 MostrarMenuController
    rectangle #F2AC4E PermisosRepository
    rectangle #F2AC4E OpcionesMenu
    rectangle #F2AC4E Sesion
}

rectangle #CDEBA5 ":Collaboration AbrirProgramas" as AbrirProgramas
rectangle #CDEBA5 ":Collaboration AbrirCursos" as AbrirCursos
rectangle #CDEBA5 ":Collaboration AbrirProfesores" as AbrirProfesores
rectangle #CDEBA5 ":Collaboration AbrirEdificios" as AbrirEdificios
rectangle #CDEBA5 ":Collaboration AbrirAulas" as AbrirAulas
rectangle #CDEBA5 ":Collaboration AbrirRecursos" as AbrirRecursos
rectangle #CDEBA5 ":Collaboration AsignarProfesor" as AsignarProfesor
rectangle #CDEBA5 ":Collaboration GenerarHorario" as GenerarHorario
rectangle #CDEBA5 ":Collaboration ConsultarHorario" as ConsultarHorario
rectangle #CDEBA5 ":Collaboration CerrarSesion" as CerrarSesion

Administrador -r-> MenuView
note on link
    disponibilizarSistema()
end note

MenuView -d-> MostrarMenuController
note on link
    habilitarOpciones(administrador)
end note

MostrarMenuController --> Sesion
note on link
    getUsuario() : Usuario
end note

MostrarMenuController --> PermisosRepository
note on link
    obtenerOpciones(usuario) : List<Opcion>
end note

MostrarMenuController --> OpcionesMenu
note on link
    crearOpciones(opciones) : OpcionesMenu
end note

MenuView --> OpcionesMenu
note on link
    getOpciones() : List<Opcion>
end note

'Administrador --> MenuView : abrirProgramas()
MenuView ..> AbrirProgramas
note on link
    abrirProgramas()
end note

'Administrador --> MenuView : abrirCursos()
MenuView ..> AbrirCursos
note on link
    abrirCursos()
end note

'Administrador --> MenuView : abrirProfesores()
MenuView ..> AbrirProfesores
note on link
    abrirProfesores()
end note

'Administrador --> MenuView : abrirEdificios()
MenuView ..> AbrirEdificios
note on link
    abrirEdificios()
end note

'Administrador --> MenuView : abrirAulas()
MenuView ..> AbrirAulas
note on link
    abrirAulas()
end note

'Administrador --> MenuView : abrirRecursos()
MenuView ..> AbrirRecursos
note on link
    abrirRecursos()
end note

'Administrador --> MenuView : asignarProfesorACurso()
MenuView ..> AsignarProfesor
note on link
    asignarProfesorACurso()
end note

'Administrador --> MenuView : generarHorario()
MenuView ..> GenerarHorario
note on link
    generarHorario()
end note

'Administrador --> MenuView : consultarHorario()
MenuView ..> ConsultarHorario
note on link
    consultarHorario()
end note

'Administrador --> MenuView : cerrarSesion()
MenuView ..> CerrarSesion
note on link
    cerrarSesion()
end note

@enduml