@startuml

skinparam linetype polyline

state login as "login()" {

    state " " as RequiringCredentials
    state " " as ProvidingCredentials
    state c <<choice>>

    [*] -[#green]-> RequiringCredentials 
    note on link
    <b>UsuarioNoRegistrado</b> solicita acceder
    end note    
    
    RequiringCredentials -[#green]-> ProvidingCredentials
    note on link
    <b>Sistema</b> permite introducir
    • usuario
    • contraseña
    end note
    
    ProvidingCredentials -[#green]-> c
    note on link
    <b>UsuarioNoRegistrado</b> introduce
    • usuario
    • contraseña
    end note
    
    c -[#red]-> RequiringCredentials
    note on link
    usuario:contraseña
    no es válida
    end note

    c -[#green]-> [*]
}

login -[#green]-> OPENED_DASHBOARD
note on link
UsuarioNoRegistrado → Administrador
openDashboard()
end note

@enduml