@startuml diagrama-contexto-administrador

left to right direction
skinparam linetype polyline

legend bottom right
    **Leyenda de Estados RUP**
    ====
    |<#gray>     | Identificado (no iniciado) |
    |<#red>      | Detalle/Prototipado |
    |<#darkgoldenrod>| Análisis |
    |<#green>    | Diseño |
    |<#lightblue>| Desarrollo |
    |<#blue>     | Pruebas |
    |<#black>    | Completado |
    | ... |Identificado|
    | --- |En trabajo activo|
    ----
    **Enlaces de Navegación**
    ====
    Los casos de uso analizados incluyen 2 enlaces:
    [nombreCasoUso] Especificación detallada
    [A] Análisis MVC
end legend

state "SESION_CERRADA" as NoAuth
state "SISTEMA_DISPONIBLE" as Menu

state "PROGRAMAS_ABIERTO" as ListProgramas
state "PROGRAMA_ABIERTO" as EditPrograma
state "CURSOS_ABIERTO" as ListCursos
state "CURSO_ABIERTO" as EditCurso
state "PROFESORES_ABIERTO" as ListProfesores
state "PROFESOR_ABIERTO" as EditProfesor
state "PROFESOR_PREFERENCIAS_ABIERTO" as EditProfesorPreferencias
state "EDIFICIOS_ABIERTO" as ListEdificios
state "EDIFICIO_ABIERTO" as EditEdificio
state "AULAS_ABIERTO" as ListAulas
state "AULA_ABIERTA" as EditAula
state "RECURSOS_ABIERTO" as ListRecursos
state "RECURSO_ABIERTO" as EditRecurso

state "PROFESOR_ASIGNATURAS_ABIERTO" as Asignaciones
state "HORARIO_GENERADO" as Generacion
state "HORARIO_ABIERTO" as Consulta

NoAuth -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/iniciarSesion/README.md iniciarSesion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/iniciarSesion/README.md A]]

Menu -[#darkgoldenrod,thickness=2]-> NoAuth: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/cerrarSesion/README.md cerrarSesion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/cerrarSesion/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProgramas/README.md abrirProgramas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProgramas/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirCursos/README.md abrirCursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirCursos/README.md A]]
Menu -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProfesores/README.md abrirProfesores()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProfesores/README.md A]]
Menu -[#darkgoldenrod]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirEdificios/README.md abrirEdificios()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirEdificios/README.md A]]
Menu -[#darkgoldenrod]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirAulas/README.md abrirAulas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirAulas/README.md A]]
Menu -[#darkgoldenrod]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirRecursos/README.md abrirRecursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirRecursos/README.md A]]
Menu -[#gray,dotted]-> Generacion: generarHorario()
Menu -[#gray,dotted]-> Consulta: consultarHorario()

EditProfesor -[#gray,dotted]-> Asignaciones: asignarProfesorACurso()

Asignaciones -[#gray,dotted]-> Asignaciones: asignarProfesorACurso()
Asignaciones -[#gray,dotted]-> EditProfesor: editarProfesor()
ListProgramas -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/crearPrograma/README.md crearPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/crearPrograma/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarPrograma/README.md editarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarPrograma/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarPrograma/README.md eliminarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarPrograma/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> EditPrograma: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/editarPrograma/README.md editarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/editarPrograma/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/eliminarPrograma/README.md eliminarPrograma()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/eliminarPrograma/README.md A]]
EditPrograma -[#darkgoldenrod,thickness=2]-> ListProgramas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProgramas/README.md abrirProgramas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProgramas/README.md A]]
ListCursos -[#gray,dotted]-> EditCurso: crearCurso()
ListCursos -[#gray,dotted]-> EditCurso: editarCurso()
ListCursos -[#gray,dotted]-> ListCursos: eliminarCurso()
EditCurso -[#gray,dotted]-> EditCurso: editarCurso()
EditCurso -[#darkgoldenrod,thickness=2]-> ListCursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirCursos/README.md abrirCursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirCursos/README.md A]]
ListProfesores -[#gray,dotted]-> EditProfesor: crearProfesor()
ListProfesores -[#gray,dotted]-> EditProfesor: editarProfesor()
ListProfesores -[#gray,dotted]-> ListProfesores: eliminarProfesor()
EditProfesor -[#gray,dotted]-> EditProfesor: editarProfesor()
EditProfesor -[#gray,dotted]-> EditProfesorPreferencias: configurarPreferenciasProfesor()
EditProfesor -[#darkgoldenrod,thickness=2]-> ListProfesores: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirProfesores/README.md abrirProfesores()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirProfesores/README.md A]]
EditProfesorPreferencias -[#gray,dotted]-> EditProfesorPreferencias: configurarPreferenciasProfesor()
EditProfesorPreferencias -[#gray,dotted]-> EditProfesor: abrirEdicionProfesor()
ListEdificios -[#gray,dotted]-> EditEdificio: crearEdificio()
ListEdificios -[#gray,dotted]-> EditEdificio: editarEdificio()
ListEdificios -[#gray,dotted]-> ListEdificios: eliminarEdificio()
EditEdificio -[#gray,dotted]-> EditEdificio: editarEdificio()
EditEdificio -[#darkgoldenrod]-> ListEdificios: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirEdificios/README.md abrirEdificios()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirEdificios/README.md A]]
ListAulas -[#gray,dotted]-> EditAula: crearAula()
ListAulas -[#gray,dotted]-> EditAula: editarAula()
ListAulas -[#gray,dotted]-> ListAulas: eliminarAula()
EditAula -[#gray,dotted]-> EditAula: editarAula()
EditAula -[#darkgoldenrod]-> ListAulas: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirAulas/README.md abrirAulas()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirAulas/README.md A]]
ListRecursos -[#gray,dotted]-> EditRecurso: crearRecurso()
ListRecursos -[#gray,dotted]-> EditRecurso: editarRecurso()
ListRecursos -[#gray,dotted]-> ListRecursos: eliminarRecurso()
EditRecurso -[#gray,dotted]-> EditRecurso: editarRecurso()
EditRecurso -[#darkgoldenrod]-> ListRecursos: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/abrirRecursos/README.md abrirRecursos()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/abrirRecursos/README.md A]]
ListProgramas -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
ListCursos -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
ListProfesores -[#darkgoldenrod,thickness=2]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
ListEdificios -[#darkgoldenrod]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
ListAulas -[#darkgoldenrod]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
ListRecursos -[#darkgoldenrod]-> Menu: [[https://github.com/mmasias/pySigHor/blob/main/RUP/00-casos-uso/02-detalle/completarGestion/README.md completarGestion()]] [[https://github.com/mmasias/pySigHor/blob/main/RUP/01-analisis/casos-uso/completarGestion/README.md A]]
Generacion -[#darkgoldenrod,thickness=2]-> Menu: completarProceso()
Consulta -[#darkgoldenrod,thickness=2]-> Menu: completarConsulta()
@enduml