services:
  db:
    image: postgres:15
    container_name: university_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: timetable_admin
      POSTGRES_PASSWORD: timetable_pass
      POSTGRES_DB: timetable
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: university_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: