@startuml

left to right direction

state "NO_AUTENTICADO" as NoAuth
state "AUTENTICANDO" as PreMenu
state "MENU_PRINCIPAL" as Menu

state "LISTANDO_PROGRAMAS" as ListProgramas
state "EDITANDO_PROGRAMA" as EditPrograma
state "LISTANDO_CURSOS" as ListCursos
state "EDITANDO_CURSO" as EditCurso
state "LISTANDO_PROFESORES" as ListProfesores
state "EDITANDO_PROFESOR" as EditProfesor
state "LISTANDO_EDIFICIOS" as ListEdificios
state "EDITANDO_EDIFICIO" as EditEdificio
state "LISTANDO_AULAS" as ListAulas
state "EDITANDO_AULA" as EditAula
state "LISTANDO_RECURSOS" as ListRecursos
state "EDITANDO_RECURSO" as EditRecurso

state "CONFIGURANDO_ASIGNACIONES" as Asignaciones
state "GENERANDO_HORARIO" as Generacion
state "CONSULTANDO_HORARIOS" as Consulta

[*] --> NoAuth

PreMenu --> NoAuth
    note on link
        iniciarSesion(error)
    end note

NoAuth --> PreMenu
    note on link
        iniciarSesion()
    end note

PreMenu --> Menu
    note on link
        mostrarMenu()
    end note

Menu --> NoAuth
    note on link
        cerrarSesion()
    end note

Menu --> ListProgramas
    note on link
        listarProgramas()
    end note

Menu --> ListCursos
    note on link
        listarCursos()
    end note

Menu --> ListProfesores
    note on link
        listarProfesores()
    end note

Menu --> ListEdificios
    note on link
        listarEdificios()
    end note

Menu --> ListAulas
    note on link
        listarAulas()
    end note

Menu --> ListRecursos
    note on link
        listarRecursos()
    end note

Menu --> Asignaciones
    note on link
        asignarProfesorACurso()
    end note

Menu --> Generacion
    note on link
        generarHorario()
    end note

Menu --> Consulta
    note on link
        consultarHorario()
    end note

ListProgramas --> EditPrograma
    note on link
        crearPrograma()
    end note

ListProgramas --> EditPrograma
    note on link
        editarPrograma()
    end note

ListProgramas --> ListProgramas
    note on link
        eliminarPrograma()
    end note

EditPrograma --> EditPrograma
    note on link
        editarPrograma()
    end note

EditPrograma --> ListProgramas
    note on link
        listarProgramas()
    end note

ListCursos --> EditCurso
    note on link
        crearCurso()
        editarCurso()
    end note

ListCursos --> ListCursos
    note on link
        eliminarCurso()
    end note

EditCurso --> EditCurso
    note on link
        editarCurso()
    end note

EditCurso --> ListCursos
    note on link
        listarCursos()
    end note

ListProfesores --> EditProfesor
    note on link
        crearProfesor()
        editarProfesor()
    end note

ListProfesores --> ListProfesores
    note on link
        eliminarProfesor()
    end note

EditProfesor --> EditProfesor
    note on link
        editarProfesor()
        configurarPreferenciasProfesor()
    end note

EditProfesor --> ListProfesores
    note on link
        listarProfesores()
    end note

ListEdificios --> EditEdificio
    note on link
        crearEdificio()
        editarEdificio()
    end note

ListEdificios --> ListEdificios
    note on link
        eliminarEdificio()
    end note

EditEdificio --> EditEdificio
    note on link
        editarEdificio()
    end note

EditEdificio --> ListEdificios
    note on link
        listarEdificios()
    end note

ListAulas --> EditAula
    note on link
        crearAula()
        editarAula()
    end note

ListAulas --> ListAulas
    note on link
        eliminarAula()
    end note

EditAula --> EditAula
    note on link
        editarAula()
    end note

EditAula --> ListAulas
    note on link
        listarAulas()
    end note

ListRecursos --> EditRecurso
    note on link
        crearRecurso()
        editarRecurso()
    end note

ListRecursos --> ListRecursos
    note on link
        eliminarRecurso()
    end note

EditRecurso --> EditRecurso
    note on link
        editarRecurso()
    end note

EditRecurso --> ListRecursos
    note on link
        listarRecursos()
    end note

ListProgramas --> Menu
    note on link
        mostrarMenu()
    end note

ListCursos --> Menu
    note on link
        mostrarMenu()
    end note

ListProfesores --> Menu
    note on link
        mostrarMenu()
    end note

ListEdificios --> Menu
    note on link
        mostrarMenu()
    end note

ListAulas --> Menu
    note on link
        mostrarMenu()
    end note

ListRecursos --> Menu
    note on link
        mostrarMenu()
    end note

Asignaciones --> Menu
    note on link
        mostrarMenu()
    end note

Generacion --> Menu
    note on link
        mostrarMenu()
    end note

Consulta --> Menu
    note on link
        mostrarMenu()
    end note

@enduml