@startuml listarCursos

skinparam linetype polyline

state listarCursos as "listarCursos()" {

    state " " as MostrandoLista
    state " " as FiltrandoLista

    [*] -[#green]-> MostrandoLista 
    note on link
    <b>Administrador</b> solicita listar cursos
    end note    
    
    MostrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Sistema</b> presenta lista de cursos
    • Código, nombre, descripción de cada curso
    • Permite solicitar filtrar lista
    • Permite solicitar crear curso nuevo
    • Permite solicitar eliminar curso
    • Permite solicitar editar curso
    end note
    
    FiltrandoLista -[#green]-> FiltrandoLista
    note on link
    <b>Administrador</b> solicita filtrar lista
    <b>Sistema</b> presenta lista filtrada
    end note
    
    FiltrandoLista -[#green]-> [*]
    note on link
    <b>Administrador</b> solicita una de las opciones
    end note
}

listarCursos -[#green]-> EDITANDO_CURSO
note on link
editarCurso()
end note

listarCursos -[#green]-> EDITANDO_CURSO
note on link
crearCurso()
end note

listarCursos -[#green]-> LISTANDO_CURSOS
note on link
eliminarCurso()
end note

listarCursos -[#green]-> MENU_PRINCIPAL
note on link
mostrarMenu()
end note

@enduml